version: '3'
services:

  bokehhub:
    build: .
    ports: 
      - '8003:8000'
    volumes:
      - ~/bokehhub/datasets:/usr/src/bokehhub/bokehserver/data/datasets
      - ~/bokehhub/plots:/usr/src/bokehhub/bokehserver/plots
      - ~/bokehhub/config:/usr/src/bokehhub/config
    restart: always

  redis:
    image: "redis:alpine"
    restart: always